### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/const_fn#38]
Tracking issue for the 1.0 release.

**Blockers:**

- [ ] stabilization of `cfg(version)` https://github.com/rust-lang/rust/issues/64796

**TODO:**

Once blockers resolved, do the following things:

- [ ] implement #28 "Remove const_fn(nightly) in favor of custom cfgs"
- [ ] add more docs (consistency of behavior with `cfg(version)` (#35), etc.)
